name: Deploy DocxToPdf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show files in workspace
        run: ls

      - name: Set up Java version
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: '17'

      - name: Install MS Office
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Test DocxToPdf converter
        run: gradle test --tests DocxToPdfTest

      - name: Package api into a .jar
        run: jar cf DocxToPdf.jar .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: DocxToPdf
          path: ./*.jar

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: DocxToPdf

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DocxToPdf'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          package: '*.jar'
